### ISSUE TITLE
Run test from CLI

### ISSUE THREAD

**Issue by ErreVega** [steineey/node-red-contrib-flowtest#1]
Hello,

I haven't tried this yet, but it's  very interesting. however I have a doubt.

Could these tests be run via a CLI? Like "npm test" or something like that so I can include them in a CI/CD pipeline.

Thanks!

**Comment by csteinba** [comment]
Hi ErreVega,

this package was intended to define and execute test cases inside node-red's editor in the first place. The tests are executed right after you click the flow deploy button and will give you an instant feedback.

If you want to integrate these kind of testing inside a CI/CD pipeline you have to run the node-red runtime inside your pipeline. The test inject node will inject your test cases right after the runtime is up. You could use the second output of the inject node to output the test results for your CI/CD pipeline.
